## Implementação de uma MLP para realizar a predição se um câncer é maligno ou benigno

## Tratamento do Dataset

In [149]:
import pandas as pd

#### Como podemos observar, o dataset tem como entrada:

In [150]:
data = pd.read_csv('datasets/Breast_cancer_wisconsin_dataset.csv')
data

,ID,Clump Thickness,Uniformity of Cell Size,Uniformity of Cell Shape,Marginal Adhesion,Single Epithelial Cell Size,Bare Nuclei,Bland Chromatin,Normal Nucleoli,Mitoses,Class
0,1000025,5,1,1,1,2,1,3,1,1,2
1,1002945,5,4,4,5,7,10,3,2,1,2
2,1015425,3,1,1,1,2,2,3,1,1,2
3,1016277,6,8,8,1,3,4,3,7,1,2
4,1017023,4,1,1,3,2,1,3,1,1,2
5,1017122,8,10,10,8,7,10,9,7,1,4
6,1018099,1,1,1,1,2,10,3,1,1,2
7,1018561,2,1,2,1,2,1,3,1,1,2
8,1033078,2,1,1,1,2,1,1,1,5,2
9,1033078,4,2,1,1,2,1,2,1,1,2
10,1035283,1,1,1,1,1,1,3,1,1,2
11,1036172,2,1,1,1,2,1,2,1,1,2
12,1041801,5,3,3,3,2,3,4,4,1,4
13,1043999,1,1,1,1,2,3,3,1,1,2
14,1044572,8,7,5,10,7,9,5,5,4,4
15,1047630,7,4,6,4,6,1,4,3,1,4
16,1048672,4,1,1,1,2,1,2,1,1,2
17,1049815,4,1,1,1,2,1,3,1,1,2
18,1050670,10,7,7,6,4,10,4,1,2,4
19,1050718,6,1,1,1,2,1,3,1,1,2
20,1054590,7,3,2,10,5,10,5,4,4,4
21,1054593,10,5,5,3,6,7,7,10,1,4
22,1056784,3,1,1,1,2,1,2,1,1,2
23,1057013,8,4,5,1,2,?,7,3,1,4
24,1059552,1,1,1,1,2,1,3,1,1,2
25,1065726,5,2,3,4,2,7,3,6,1,4
26,1066373,3,2,1,1,1,1,2,1,1,2
27,1066979,5,1,1,1,2,1,2,1,1,2
28,1067444,2,1,1,1,2,1,2,1,1,2
29,1070935,1,1,3,1,2,1,1,1,1,2
...,...,...,...,...,...,...,...,...,...,...,...
669,1350423,5,10,10,8,5,5,7,10,1,4
670,1352848,3,10,7,8,5,8,7,4,1,4
671,1353092,3,2,1,2,2,1,3,1,1,2
672,1354840,2,1,1,1,2,1,3,1,1,2
673,1354840,5,3,2,1,3,1,1,1,1,2
674,1355260,1,1,1,1,2,1,2,1,1,2
675,1365075,4,1,4,1,2,1,1,1,1,2
676,1365328,1,1,2,1,2,1,2,1,1,2
677,1368267,5,1,1,1,2,1,1,1,1,2
678,1368273,1,1,1,1,2,1,1,1,1,2
679,1368882,2,1,1,1,2,1,1,1,1,2
680,1369821,10,10,10,10,5,10,10,10,7,4
681,1371026,5,10,10,10,4,10,5,6,3,4
682,1371920,5,1,1,1,2,1,3,2,1,2
683,466906,1,1,1,1,2,1,1,1,1,2
684,466906,1,1,1,1,2,1,1,1,1,2
685,534555,1,1,1,1,2,1,1,1,1,2
686,536708,1,1,1,1,2,1,1,1,1,2
687,566346,3,1,1,1,2,1,2,3,1,2
688,603148,4,1,1,1,2,1,1,1,1,2
689,654546,1,1,1,1,2,1,1,1,8,2
690,654546,1,1,1,3,2,1,1,1,1,2
691,695091,5,10,10,5,4,5,4,4,1,4
692,714039,3,1,1,1,2,1,1,1,1,2
693,763235,3,1,1,1,2,1,2,1,2,2
694,776715,3,1,1,1,3,2,1,1,1,2
695,841769,2,1,1,1,2,1,1,1,1,2
696,888820,5,10,10,3,7,3,8,10,2,4
697,897471,4,8,6,4,3,4,10,6,1,4
698,897471,4,8,8,5,4,5,10,4,1,4

In [151]:
##Exclusão do campo Id, pois não será relevante para o algoritmo
data.drop('ID',inplace=True,axis=1)

In [152]:
data.isnull().sum()## como podemos observar, não há elementos nulos em nenhuma das campos

Clump Thickness                0
Uniformity of Cell Size        0
Uniformity of Cell Shape       0
Marginal Adhesion              0
Single Epithelial Cell Size    0
Bare Nuclei                    0
Bland Chromatin                0
Normal Nucleoli                0
Mitoses                        0
Class                          0
dtype: int64

In [153]:
## Agora será substituido o valor 2 do campo class por 0(benigno) e 4 por 1(maligno)
for i, row in data.iterrows():
    if row['Class']==2:
        data.loc[i,'Class'] = 0
    else:
        data.loc[i,'Class'] = 1

In [162]:
import numpy as np
def correcao_valores(df):
    result = df.copy()
    for feature_name in result.columns:
        #print(feature_name)
        mean = np.mean(pd.to_numeric(df[feature_name], errors='coerce'))
        
        for i, row in result.iterrows():
            aux = row[feature_name]
            if not str(row[feature_name]).isdigit():
                result.loc[i,feature_name] =mean
                aux = mean
                
            result.loc[i,feature_name]=float(aux)
    return result
df = correcao_valores(data)

In [163]:
def normalize(df):
    result = df.copy()
    for feature_name in df.columns:
        max_value = df[feature_name].max()
        min_value = df[feature_name].min()
        result[feature_name] = (df[feature_name] - min_value) / (max_value - min_value)
    return result
dn = normalize(df)

Clump Thickness
Uniformity of Cell Size
Uniformity of Cell Shape
Marginal Adhesion
Single Epithelial Cell Size
Bare Nuclei
Bland Chromatin
Normal Nucleoli
Mitoses
Class

In [164]:
dn

,Clump Thickness,Uniformity of Cell Size,Uniformity of Cell Shape,Marginal Adhesion,Single Epithelial Cell Size,Bare Nuclei,Bland Chromatin,Normal Nucleoli,Mitoses,Class
0,0.444444,0.000000,0.000000,0.000000,0.111111,0,0.222222,0.000000,0.000000,0.0
1,0.444444,0.333333,0.333333,0.444444,0.666667,1,0.222222,0.111111,0.000000,0.0
2,0.222222,0.000000,0.000000,0.000000,0.111111,0.111111,0.222222,0.000000,0.000000,0.0
3,0.555556,0.777778,0.777778,0.000000,0.222222,0.333333,0.222222,0.666667,0.000000,0.0
4,0.333333,0.000000,0.000000,0.222222,0.111111,0,0.222222,0.000000,0.000000,0.0
5,0.777778,1.000000,1.000000,0.777778,0.666667,1,0.888889,0.666667,0.000000,1.0
6,0.000000,0.000000,0.000000,0.000000,0.111111,1,0.222222,0.000000,0.000000,0.0
7,0.111111,0.000000,0.111111,0.000000,0.111111,0,0.222222,0.000000,0.000000,0.0
8,0.111111,0.000000,0.000000,0.000000,0.111111,0,0.000000,0.000000,0.444444,0.0
9,0.333333,0.111111,0.000000,0.000000,0.111111,0,0.111111,0.000000,0.000000,0.0
10,0.000000,0.000000,0.000000,0.000000,0.000000,0,0.222222,0.000000,0.000000,0.0
11,0.111111,0.000000,0.000000,0.000000,0.111111,0,0.111111,0.000000,0.000000,0.0
12,0.444444,0.222222,0.222222,0.222222,0.111111,0.222222,0.333333,0.333333,0.000000,1.0
13,0.000000,0.000000,0.000000,0.000000,0.111111,0.222222,0.222222,0.000000,0.000000,0.0
14,0.777778,0.666667,0.444444,1.000000,0.666667,0.888889,0.444444,0.444444,0.333333,1.0
15,0.666667,0.333333,0.555556,0.333333,0.555556,0,0.333333,0.222222,0.000000,1.0
16,0.333333,0.000000,0.000000,0.000000,0.111111,0,0.111111,0.000000,0.000000,0.0
17,0.333333,0.000000,0.000000,0.000000,0.111111,0,0.222222,0.000000,0.000000,0.0
18,1.000000,0.666667,0.666667,0.555556,0.333333,1,0.333333,0.000000,0.111111,1.0
19,0.555556,0.000000,0.000000,0.000000,0.111111,0,0.222222,0.000000,0.000000,0.0
20,0.666667,0.222222,0.111111,1.000000,0.444444,1,0.444444,0.333333,0.333333,1.0
21,1.000000,0.444444,0.444444,0.222222,0.555556,0.666667,0.666667,1.000000,0.000000,1.0
22,0.222222,0.000000,0.000000,0.000000,0.111111,0,0.111111,0.000000,0.000000,0.0
23,0.777778,0.333333,0.444444,0.000000,0.111111,0.28274,0.666667,0.222222,0.000000,1.0
24,0.000000,0.000000,0.000000,0.000000,0.111111,0,0.222222,0.000000,0.000000,0.0
25,0.444444,0.111111,0.222222,0.333333,0.111111,0.666667,0.222222,0.555556,0.000000,1.0
26,0.222222,0.111111,0.000000,0.000000,0.000000,0,0.111111,0.000000,0.000000,0.0
27,0.444444,0.000000,0.000000,0.000000,0.111111,0,0.111111,0.000000,0.000000,0.0
28,0.111111,0.000000,0.000000,0.000000,0.111111,0,0.111111,0.000000,0.000000,0.0
29,0.000000,0.000000,0.222222,0.000000,0.111111,0,0.000000,0.000000,0.000000,0.0
...,...,...,...,...,...,...,...,...,...,...
669,0.444444,1.000000,1.000000,0.777778,0.444444,0.444444,0.666667,1.000000,0.000000,1.0
670,0.222222,1.000000,0.666667,0.777778,0.444444,0.777778,0.666667,0.333333,0.000000,1.0
671,0.222222,0.111111,0.000000,0.111111,0.111111,0,0.222222,0.000000,0.000000,0.0
672,0.111111,0.000000,0.000000,0.000000,0.111111,0,0.222222,0.000000,0.000000,0.0
673,0.444444,0.222222,0.111111,0.000000,0.222222,0,0.000000,0.000000,0.000000,0.0
674,0.000000,0.000000,0.000000,0.000000,0.111111,0,0.111111,0.000000,0.000000,0.0
675,0.333333,0.000000,0.333333,0.000000,0.111111,0,0.000000,0.000000,0.000000,0.0
676,0.000000,0.000000,0.111111,0.000000,0.111111,0,0.111111,0.000000,0.000000,0.0
677,0.444444,0.000000,0.000000,0.000000,0.111111,0,0.000000,0.000000,0.000000,0.0
678,0.000000,0.000000,0.000000,0.000000,0.111111,0,0.000000,0.000000,0.000000,0.0
679,0.111111,0.000000,0.000000,0.000000,0.111111,0,0.000000,0.000000,0.000000,0.0
680,1.000000,1.000000,1.000000,1.000000,0.444444,1,1.000000,1.000000,0.666667,1.0
681,0.444444,1.000000,1.000000,1.000000,0.333333,1,0.444444,0.555556,0.222222,1.0
682,0.444444,0.000000,0.000000,0.000000,0.111111,0,0.222222,0.111111,0.000000,0.0
683,0.000000,0.000000,0.000000,0.000000,0.111111,0,0.000000,0.000000,0.000000,0.0
684,0.000000,0.000000,0.000000,0.000000,0.111111,0,0.000000,0.000000,0.000000,0.0
685,0.000000,0.000000,0.000000,0.000000,0.111111,0,0.000000,0.000000,0.000000,0.0
686,0.000000,0.000000,0.000000,0.000000,0.111111,0,0.000000,0.000000,0.000000,0.0
687,0.222222,0.000000,0.000000,0.000000,0.111111,0,0.111111,0.222222,0.000000,0.0
688,0.333333,0.000000,0.000000,0.000000,0.111111,0,0.000000,0.000000,0.000000,0.0
689,0.000000,0.000000,0.000000,0.000000,0.111111,0,0.000000,0.000000,0.777778,0.0
690,0.000000,0.000000,0.000000,0.222222,0.111111,0,0.000000,0.000000,0.000000,0.0
691,0.444444,1.000000,1.000000,0.444444,0.333333,0.444444,0.333333,0.333333,0.000000,1.0
692,0.222222,0.000000,0.000000,0.000000,0.111111,0,0.000000,0.000000,0.000000,0.0
693,0.222222,0.000000,0.000000,0.000000,0.111111,0,0.111111,0.000000,0.111111,0.0
694,0.222222,0.000000,0.000000,0.000000,0.222222,0.111111,0.000000,0.000000,0.000000,0.0
695,0.111111,0.000000,0.000000,0.000000,0.111111,0,0.000000,0.000000,0.000000,0.0
696,0.444444,1.000000,1.000000,0.222222,0.666667,0.222222,0.777778,1.000000,0.111111,1.0
697,0.333333,0.777778,0.555556,0.333333,0.222222,0.333333,1.000000,0.555556,0.000000,1.0
698,0.333333,0.777778,0.777778,0.444444,0.333333,0.444444,1.000000,0.333333,0.000000,1.0